name: Create Redshift schema and tables

on:
  push:
    branches: [ main ]
env:
 AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  create_redshift_schema_and_tables:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ env.AWS_ACCESS_ID }}
       aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ env.AWS_REGION }}
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Create Redshift schema and tables
      run: |
       sql -h redshift-cluster-1.ceasvzfizbth.ap-south-1.redshift.amazonaws.com:5439/dev -p 5439 -U awsuser -d dev -f redshift.sql 
