name: Create Redshift schema and tables

on:
  push:
    branches: [ main ]

jobs:
  create_redshift_schema_and_tables:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Create Redshift schema and tables
      run: |
        aws redshift-data execute-statement --cluster-identifier my-cluster --database my-db --sql file://redshift.sql
